//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airvibes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AVdataEntitiesSettings : DbContext
    {
        public AVdataEntitiesSettings()
            : base("name=AVdataEntitiesSettings")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artists> Artists { get; set; }
        public virtual DbSet<Covers> Covers { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<RComment> RComment { get; set; }
        public virtual DbSet<Records> Records { get; set; }
        public virtual DbSet<SComment> SComment { get; set; }
        public virtual DbSet<Songs> Songs { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
