//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airvibes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RComments
    {
        public int Id { get; set; }
        public int Id_User { get; set; }
        public int Id_Record { get; set; }
        public string Body { get; set; }
        public System.DateTime PostedAt { get; set; }
        public Nullable<int> Records_Id { get; set; }
        public Nullable<int> Users_Id { get; set; }
    
        public virtual Records Records { get; set; }
        public virtual Users Users { get; set; }
    }
}
